### ISSUE TITLE
`egui_extras` access

### ISSUE THREAD

**Issue by no-materials** [mvlabat/bevy_egui#102]
Will the `egui_extras` lib be accessible through `bevy_egui`?

**Comment by mvlabat** [comment]
Hi! I had no such plans, but in theory it's possible to expose it and make it feature gated. But if it wasn't done in Egui itself, I'm not sure whether we should. Is there any particular reason why you want to have it in `bevy_egui` instead of depending on it directly in your project?

**Comment by no-materials** [comment]
No worries, I'll just use it directly. :)
