### ISSUE TITLE
Allow using custom fonts from the asset server

### ISSUE THREAD

**Issue by Azorlogh** [mvlabat/bevy_egui#103]
It would be nice if we could use fonts obtained from the asset server. I'm not sure how feasible that would be or what the api would look like.

**Comment by mvlabat** [comment]
Hi! Apologies for the late response.

I saw that `EguiContext` has a method called `set_fonts` accepting `FontDefinitions`, which can be initialized with custom `.ttf` or `.otf` fonts. I've never used it, but I reckon it would be enough to just retrieve the bytes from the `Assets` resource, create `FontDefinitions` and pass them to that method.

Not sure if there's much that `bevy_egui` can provide itself in terms of API, but we can probably create an example to show how to work with custom fonts.

Let me know if that helps.

**Comment by mvlabat** [comment]
I assume this answers the question so I'll close the issue. But feel free to comment or open a new one if you have any questions remaining.

**Comment by SludgePhD** [comment]
I don't think there is a way to obtain the bytes that make up a bevy `Font`, at least not with the reworked asset system. A custom asset type or loader could probably do it, but it would be nice to have a more convenient way to do it.
