### ISSUE TITLE
outdated/invalid links in documentation

### ISSUE THREAD

**Issue by Ryder17z** [mvlabat/bevy_egui#114]
from https://docs.rs/bevy_egui/0.14.0/bevy_egui/ 

`Multiple windows support (see [./examples/two_windows.rs](https://docs.rs/bevy_egui/0.14.0/bevy_egui/examples/two_windows.rs))`

`For a more advanced example, see [examples/ui.rs](https://docs.rs/bevy_egui/0.14.0/bevy_egui/examples/ui.rs).`

These links give a 404 when clicked.

**Comment by mvlabat** [comment]
Good catch! I fixed the links in the new version. Thanks
