### ISSUE TITLE
Does Bevy Egui Need the Bevy PBR Dependency?

### ISSUE THREAD

**Issue by zicklag** [mvlabat/bevy_egui#117]
Hey there!

I'm using `bevy_egui` in my 2D game and I noticed that Bevy Egui is causing it to depend on Bevy PBR. Is this dependency necessary?

Would you be open to removing the dependency if possible?

**Comment by zicklag** [comment]
Sorry for the noise, I was mistaken and notice now that that's only for the examples!

**Comment by mvlabat** [comment]
No worries! Glad it was figured out :)
