### ISSUE TITLE
`add_image` drops strong handles

### ISSUE THREAD

**Issue by TheRawMeatball** [mvlabat/bevy_egui#119]
`EguiContext::add_image` should internally continue to store strong handles so the underlying textures are kept alive.

**Comment by mvlabat** [comment]
Oh, right, after one of the updates we changed the way how we store handles: instead of handles themselves, we just store `HandleId` now. I can make the fix by the end of the week, but I'll gladly accept a PR as well.

That was a good catch, thank you!

**Comment by mvlabat** [comment]
Fixed in 0.15.1.
