### ISSUE TITLE
Mouse press state gets weird on right click (context menu)

### ISSUE THREAD

**Issue by RobWalt** [mvlabat/bevy_egui#122]
Just an example here:

To reproduce:

- go to [the example](https://mvlabat.github.io/bevy_egui_web_showcase/index.html)
- hover mouse over canvas
- press right mouse button
- close it by clicking left mouse button anywhere within the app
- mouse button state is pressed even if I don't press the mouse -> continuously drawing on canvas 

![image](https://user-images.githubusercontent.com/26892280/190104585-48e84867-73f8-483c-bdbf-2ff45dce5855.png)

1. mouse right click spot
2. mouse left click spot
3. the line after this is drawn without any mouse buttons pressed

--- 

Note that this screws up other ui elements aswell:
- Buttons become partially irresponsive
- Windows can't be moved
(These are harder to reproduce but happen for some combinations of right-and-then-left-click positions)

**Comment by RobWalt** [comment]
Additional infos:

- I reproduced this behavior both in Chromium and Firefox
- Just a thought: Maybe the issue comes from `egui` itself, I wasn't able to test that

**Comment by mvlabat** [comment]
Hi @RobWalt! Thanks for creating the issue.

We should try to look into what kind of events `winit` fires, maybe `bevy_egui` fails to react to something, or `winit` doesn't fire them at all after closing the context menu - in that case the issue has to be tracked there. Or maybe even browsers don't fire the mouse release event...

But if you don't actually need native context menus in your app, this is easy to workaround if you disable the context menu for canvas.
I haven't got a chance to document it in `bevy_egui` and I'm not sure whether what's the preferable way to do it, but here's how I implemented it in my pet project:
https://github.com/mvlabat/muddle-run/blob/8ed517ec88fe2ca1a159e0826ecc1332f441f131/bins/web_client/index.html#L121

**Comment by RobWalt** [comment]
I'm finally finding time to work on this. My first tests so far bring the following news:

- the issue isn't reproducible (for me) when running a test application with `wasm-server-runner`. It seems like opening the context menu isn't possible with that.
- when compiling to wasm and packing with `wasm-bindgen` the issue is reproducible

I started with logging the `MouseButton::pressed` events from bevy and it seems like the right mouse button is permanently pressed after the first click. Looking further into that and into your suggestions. Thanks for the inputs! @mvlabat

**Comment by RobWalt** [comment]
I cloned bevy and sneaked a log message into the `event_handler` which is used to handle the raw `winit::Event`s. It seems like the issue doesn't stem from `winit` as the `winit` log messages stop, while `MouseButton::Right` events still happen

![image](https://user-images.githubusercontent.com/26892280/209842505-e77eaccc-b089-4bb4-919a-610b15ddffb1.png)

I still need to check wether `winit` fires the release event though...

**Comment by RobWalt** [comment]
Yeah, seems like you were right. The release event isn't fired for right clicks.

![image](https://user-images.githubusercontent.com/26892280/209843437-ba31b03b-d111-464e-8d46-1e6054650070.png)

**Comment by RobWalt** [comment]
I opened [an issue upstream in the `winit` repo](https://github.com/rust-windowing/winit/issues/2608)

**Comment by RobWalt** [comment]
This was partially solved upstream in a way so that it's fine for me to close the issue here.
