### ISSUE TITLE
Window resetting every frame

### ISSUE THREAD

**Issue by laranc** [mvlabat/bevy_egui#125]
The error is shown below:
https://user-images.githubusercontent.com/67891427/191387312-f0ac7303-fb91-4415-8e17-1c86fa3bf5ee.mp4

I'm not sure what causes this as I've tried compiling the UI example and it works as intended. I can attach code if necessary as I've found it difficult to reproduce outside of my project.

**Comment by mvlabat** [comment]
Hmm, I'm afraid I can't tell by looking only at the video. I'd double-check that you can find only 1 version of `bevy_egui` installed in `Cargo.lock`, but that's unlikely the cause.

If you can share a link to your project on github or upload the code in some other way, I'll take a look.

**Comment by laranc** [comment]
Repo attached:
https://github.com/laranc/GameOfCovid

The video showed the window from the `rulesmenu.rs` file, but there is another window in `resultmenu.rs` but seeing as it's just text I wasn't fussed with not being able to interact with it.

**Comment by laranc** [comment]
Never mind, there was an error in my logic that would reset the variable given to the checkbox.
