### ISSUE TITLE
Bug: clicked() is not working for ui:label()

### ISSUE THREAD

**Issue by Nickan** [mvlabat/bevy_egui#130]
Hi guys, the code snippet below is not working, what should I do to make it work?
```
egui::Window::new("Hello").show(egui_context.ctx_mut(), |ui| {
    let response = ui.label("world");
    let response = response.interact(egui::Sense::click());
    if response.clicked() {
      println!("Click!");
    }
});
```

**Comment by mvlabat** [comment]
Hey! Apologies for the late response. Tbh, I don't know the answer off the top of my head. If this is still actual, I recommend asking in [the Egui repo](https://github.com/emilk/egui/discussions), that should be a better place to seek for support about Egui itself, so I'll close this one. (But don't feel limited asking any question regarding `bevy_egui` specifically in this repo.)
