### ISSUE TITLE
How to disable camera pan/orbit when mouse cursor is hovering any egui widgets?

### ISSUE THREAD

**Issue by AllenDang** [mvlabat/bevy_egui#135]
This is not a bug, just need some help.

I'm creating a model viewer, which uses the mouse to pan/orbit camera, and egui is used to display informations.

Current issue is, when I scroll mouse wheel in a egui window, the mouse wheel event will also be captured by bevy, which will zoom in/out the camera. Same thing happens when mouse is moved with left button down.

How can I disable camera control if the mouse cursor in hovering any egui widgets like window/panel?

**Comment by AllenDang** [comment]
I got it, following code should do the trick.
```rust
    if ctx.ctx_mut().is_pointer_over_area() {
        return;
    }
```

**Comment by mvlabat** [comment]
Hi @AllenDang! Glad you found a solution. You might as well want to use `wants_pointer_input`, it also considers dragging sliders outside of a window, etc.
