### ISSUE TITLE
FontDefinitions being overwritten

### ISSUE THREAD

**Issue by smessmer** [mvlabat/bevy_egui#160]
I've been using the following code in a startup system to set custom fonts:

```rust
const TITLE_FONT_NAME: &str = "MY_FONT_NAME";
let mut fonts = FontDefinitions::default();
fonts.font_data.insert(
    TITLE_FONT_NAME.into(),
    FontData::from_static(include_bytes!(
        "path/to/font.ttf"
    )),
);
fonts
    .families
    .entry(FontFamily::Name(TITLE_FONT_NAME.into()))
    .or_default()
    .push(TITLE_FONT_NAME.into());
egui_context.ctx_mut().set_fonts(fonts);
```

I used this by setting
```rust
FontId {
  size: 30.0,
  family: FontFamily::Name(MY_TITLE_FONT.into()),
}
```
as the font property of a `RichText` object displayed in the UI.

This worked fine in bevy 0.9 / bevy_egui 0.19. However, since migrating to bevy 0.10 / bevy_egui 0.20, this doesn't work anymore and it panics when I try to use the font, saying

```
thread 'Compute Task Pool (18)' panicked at 'FontFamily::Name("MY_FONT_NAME") is not bound to any fonts', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/epaint-0.21.0/src/text/fonts.rs:624:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (18)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.0/src/schedule/executor/multi_threaded.rs:194:60
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.0/src/task_pool.rs:376:49
```

I added some code logging the existing `FontDefinitions` in the system showing the UI right before the crash, and it seems it just has some default fonts, `MY_FONT_NAME` is missing from it.

Were there any breaking changes to bevy_egui or egui that might reset `FontDefinitions` after I set them in my startup system and before they're being accessed in the UI system? Is there a better way to set custom fonts?

**Comment by Zeenobit** [comment]
I've been having similar issues, where my Egui style isn't being applied from a startup system as it did in Bevy 0.9. I can work around the issue by having the startup system run every frame, which isn't ideal.

I checked the [ui.rs](https://github.com/mvlabat/bevy_egui/blob/main/examples/ui.rs) example, and that seems to also not apply the styles correctly as the window borders are round (whereas in the example they should be configured to have no rounding).
