### ISSUE TITLE
Panic when trying to use bevy_egui with programmatically created windows.

### ISSUE THREAD

**Issue by Themayu** [mvlabat/bevy_egui#168]
Hi. I'm currently trying to use `bevy_egui` for the UI in a game I am writing. However, I am unable to get past a *very* annoying panic with the following message:

> `EguiContexts::ctx_for_window_mut` was called for an uninitialized context (window {window}), make sure your system is run after [`EguiSet::InitContexts`] (or [`EguiStartupSet::InitContexts`] for startup systems)

This crash is occurring in the following application, in which I attempt to create an authentication window and then enter a system to control that window:

```rust
mod theme;
mod windows;

use bevy::prelude::*;
use bevy::window::ExitCondition;
use bevy::winit::{UpdateMode, WinitSettings};
use std::time::Duration;
use theme::theme;

#[derive(Debug, Clone, Default, Eq, PartialEq, Ord, PartialOrd, Hash, States)]
enum State {
	#[default]
	Auth,
	Main,
}

fn ensure_directory_tree() {
	// ...
}

fn main() {
	App::new()
		.add_plugins(
			DefaultPlugins.build().set(WindowPlugin {
				close_when_requested: true,
				exit_condition: ExitCondition::OnAllClosed,
				primary_window: None,
			})
		)
		.add_plugin(EguiPlugin)
		.add_state::<State>()
		.insert_resource(theme())
		.insert_resource(WinitSettings {
			return_from_run: false,
			focused_mode: UpdateMode::Continuous,
			unfocused_mode: UpdateMode::Reactive { max_wait: Duration::from_millis(1500) },
		})
		.add_startup_system(ensure_directory_tree)
		// Authentication window
		.add_system(windows::auth::setup.in_schedule(OnEnter(State::Auth)))
		.add_system(windows::auth.in_set(OnUpdate(State::Auth)).after(windows::auth::setup))
		// Main window
		.add_system(windows::main::setup.in_schedule(OnEnter(State::Main)))
		.add_system(windows::main.in_set(OnUpdate(State::Main)).after(windows::main::setup))
		.run();
}
```

Ignoring `windows::main` for now since it does not fire, here is the code for `windows::auth`:

```rust
use crate::theme::{Theme, self};
use bevy::prelude::*;
use bevy::render::camera::RenderTarget;
use bevy::utils::tracing::info;
use bevy::window::{PresentMode, WindowMode, WindowRef, WindowResolution};
use bevy_egui::{egui, EguiContexts};

#[derive(Resource)]
pub struct AuthState {
	camera: Entity,
	window: Entity,
}

// re-exported as simply `windows::auth`
pub fn auth(mut contexts: EguiContexts, state: Res<AuthState>, theme: Res<Theme>) {
	info!("auth system");

	let context = contexts.ctx_for_window_mut(state.window);
	context.set_visuals(theme::visuals(&theme));
	egui::CentralPanel::default().show(context, |_| {
		
	});
}

pub fn setup(mut commands: Commands) {
	info!("auth setup");

	let window = Window {
		present_mode: PresentMode::AutoVsync,
		mode: WindowMode::Windowed,
		decorations: false,

		resizable: false,
		resolution: WindowResolution::new(744.0, 442.0),

		..Default::default()
	};

	let window = commands.spawn(window).id();
	let camera = commands.spawn(Camera2dBundle {
		camera: Camera {
			target: RenderTarget::Window(WindowRef::Entity(window)),
			..Default::default()
		},

		..Default::default()
	}).id();

	let state = AuthState { camera, window };
	commands.add(|world: &mut World| {
		world.insert_resource(state);
	});
}
```

The window in question is created by `windows::auth::setup`, and we enter `windows::auth::auth` (re-exported from `windows` as `windows::auth`) immediately afterward. We immediately panic because no context has been created for the new window.

This is where I am stuck, as I cannot get `bevy_egui` to create a new context, no matter what I try. I have attempted:

- Trying to force `windows::auth::setup` to run before `EguiSets::InitContext` - this panics with the original error message.
- Chaining a call to `apply_system_buffers` followed by re-calling `bevy_egui::setup_new_windows_system` - this merely panics on an unwrap inside egui itself.
- Chaining the above followed by a second call to `apply_system_buffers` and then `bevy_egui::systems::update_window_contexts_system` - this panics with the original error message.
- Chaining the above and trying to force it to run before `EguiSets::InitContext` - this doesn't even compile.

I cannot move the creation of the window to a startup system, as this would only work for `auth` and will result in the same panic when `main` is entered. Additionally, the program can move between `State::Auth` and `State::Main` at any time, and I want to leave handling this up to systems registered with the ECS, instead of trying to hack my way around this error. Especially since none of the hacks I have been able to think of have worked.

I have spent three days dealing with this now, and it is unfortunately blocking any attempt for me to use this crate at all. Three days of asking for help on the Bevy Discord server have led me to nowhere, so I am asking for assistance here. Please help.

**Comment by mvlabat** [comment]
Hi! Thanks for filling the issue, that's an interesting use-case you have. And I'm sorry that you've had a negative experience with it. I was able to reproduce the issue and I think I understand what's causing it.
Since you're using `in_schedule OnEnter`, that makes your setup system run in the `CoreSet::StateTransitions` base set. Unfortunately, `EguiSets::InitContext` runs in the `CoreSet::PreUpdate` base set, which is run before `CoreSet::StateTransitions`. That means that initialising the contexts of the windows created during `CoreSet::StateTransitions` will happen only during the next frame.

I'm afraid there's nothing that can be done on the `bevy_egui` end to fix this (unless we move our systems to `CoreSet::StateTransitions`, but I don't fully understand the implications of this and not sure it's a good idea). I think there are several ways for your to workaround this issue:
- assume that contexts may be uninitialized and early-return from UI systems if `try_ctx_for_window_mut` returns `None`
- declare an event that wouldn't be emitted on switching the state, and read those during the `CoreSet::Last` base set to create a window (this way you won't end up running your UI systems before a window is created and initialised).

Let me know if this helps.

**Comment by mvlabat** [comment]
I'll close the issue due to inactivity. I hope my previous comment answers the question, otherwise feel free to respond here or open another issue.
