### ISSUE TITLE
Horizontal Scrolling Reversed

### ISSUE THREAD

**Issue by aevyrie** [mvlabat/bevy_egui#172]
On windows, in the bevy 0.9 version of this crate, horizontal scrolling is flipped. This was originally an issue in `egui`, which we had to fix upstream in winit: https://github.com/emilk/egui/issues/965

I haven't had the time to fully debug this yet, but it appears scrolling works as expected in egui, so something is being flipped in this crate.

**Comment by mvlabat** [comment]
https://github.com/mvlabat/bevy_egui/pull/159/files#diff-420f4e08a25299e0e1fb09f4757e1d5d027a2278f37030c09ab9c06786cfa52eL224

This should be already fixed in 0.10. Do you want it backported to 0.9?

**Comment by aevyrie** [comment]
Ah, I missed this. I appreciate the offer, but nope, I'll be able to upgrade eventually.
Thanks!
