### ISSUE TITLE
Reactive mode support

### ISSUE THREAD

**Issue by thmxv** [mvlabat/bevy_egui#176]
The egui demo has something called "reactive" mode that does not redraw continuously, usually implemented with `request_repaint_after()`. And bevy allow to use a custom main loop with `set_runner()`. However I fail to understand how to tie both of those features together. I would like to render, both the UI and the 3D viewport, only after an event.

**Comment by thmxv** [comment]
I discovered that there is no need to write a custom main loop. Bevy has already a setting to work in "reactive mode" like egui `App::new().insert_resource(WinitSettings::desktop_app())` and the two works perfectly in conjunction.

**Comment by A-Totally-Normal-Name** [comment]
> .insert_resource(WinitSettings::desktop_app())

Doesn't this make the entire app run in reactive mode? Some may only want the egui menus to run in reactive mode instead of their whole bevy app. Hence, this solution isn't necessarily the best unless I'm missing something.

**Comment by thmxv** [comment]
Yes, it makes both bevy and egui run in reactive mode, but this is what I need.
