### ISSUE TITLE
Rendering custom sprites over egui elements

### ISSUE THREAD

**Issue by morgenthum** [mvlabat/bevy_egui#186]
I'm currently using bevy_egui to draw HUD elements in my game. I also have custom sprite elements (for instance, a custom cursor) that I want to render over the egui elements.

However, I've run into an issue where these custom sprites are being rendered behind the egui elements, despite my efforts to set their Z-positions.

Any ideas how to solve this?

**Comment by mvlabat** [comment]
Hey! Apologies for avoiding the issue, I didn't have an answer to share unfortunately. If you found one, please feel free to describe the solution. I'm sure this is a popular use-case as the same question was already asked before: #112.
