### ISSUE TITLE
Egui `Window` ordering

### ISSUE THREAD

**Issue by Pieresqi** [mvlabat/bevy_egui#191]
Hi, is it possible to change the default ordering behaviour of egui `Window`s ?

I have big `X` `Window` and small `Y` `Window`. And if I drag `Y` over `X` and click on `X`, then `X` will move before `Y` and hide it.
I would like to set that if I click on window `X` it won't be moved to forefront and won't hide other windows.
Is this possible ?

**Comment by mvlabat** [comment]
Hi! Sorry, I don't have the answer, and as this question is specific to Egui itself (not the integration plugin), I'd recommend to ask this question in their repo or Discord server.

**Comment by Pieresqi** [comment]
Hi, thanks for quick answer !
After looking around I think it's related to this:
https://github.com/emilk/egui/issues/1516

Also thanks for this crate, I am enjoying it. 🙂

**Comment by Pieresqi** [comment]
Oops

**Comment by Pieresqi** [comment]
Sorry for making mess 😓

**Comment by Pieresqi** [comment]
Hi, thanks for quick answer !
After looking around I think it's related to this:
https://github.com/emilk/egui/issues/1516

Also thanks for this crate, I am enjoying it. 🙂

**Comment by mvlabat** [comment]
No worries! Thanks for linking the issue
