### ISSUE TITLE
Incompatible color attachments under WebGPU/WASM

### ISSUE THREAD

**Issue by seabassjh** [mvlabat/bevy_egui#194]
The color attachment state expects SRGB in WebGPU.  Adding it to the texture_format in `render_systems.rs` fixes this issue. 

```                
texture_format: window.swap_chain_texture_format?.add_srgb_suffix(),
```

It is unclear, however, if applying this fix unconditionally to all platforms would be a breaking change or not.  What is clear, is that this fix at least works with WebGPU.

![image](https://github.com/mvlabat/bevy_egui/assets/20546772/5ab36799-1c0a-423e-9ac5-1a2f69d36911)

I know @mvlabat and I discussed this in the bevy discord already, I just wanted to make sure this issue does not fall through the cracks

**Comment by frewsxcv** [comment]
I ran into this and opened a PR which fixes this bug for me: https://github.com/mvlabat/bevy_egui/pull/220
