### ISSUE TITLE
Save Render Image

### ISSUE THREAD

**Issue by Youdiie** [mvlabat/bevy_egui#197]
Hello I found this example(https://github.com/mvlabat/bevy_egui/blob/e57b2d31a669e1a80a42e0f459aa61a91ba305a6/examples/render_to_image_widget.rs).
Now I wonder is it possible to save this render image to file?
Any comment is helpful!

**Comment by mvlabat** [comment]
I'm not sure if the question is still actual, but I guess a better place to ask it would in Bevy Discord, since it doesn't seem to be related to `bevy_egui` API. In case I misunderstood it, feel free to reopen.
