### ISSUE TITLE
World-space UI

### ISSUE THREAD

**Issue by TheButlah** [mvlabat/bevy_egui#207]
(reposted from #193)

I would like to be able to do world-space egui based UI in bevy. Think, rendering to a wall in a game, or even a mesh like a curved computer monitor. I think this would require rendering to a bevy `Image` as an output texture. As a jank demo of what I mean, I've managed to do something similar with egui_wgpu here ([WIP code](https://github.com/TheButlah/wgpu-experiments/commit/abc18093223deec5686ad5d1432d05422f49a6be), danger).

Is there any interest in adding this as a feature to bevy_egui? I need to do make this anyway, so it probably makes sense for me to add it here instead of in another crate.

https://github.com/mvlabat/bevy_egui/assets/6969415/a4c820b0-8f67-4f01-9f94-e596cac0e722

**Comment by mvlabat** [comment]
Hey! Thanks for creating the issue. Yes, this is something I'd be absolutely happy to see in `bevy_egui`. Unfortunately, I have very limited time lately, so I don't know how long it will take me to implement this. I have some drafts locally that aren't even remotely functional, so if anyone wants to try to tackle it as well, I'll happily accept such a PR.

**Comment by TheButlah** [comment]
I've managed to get my wgpu prototype turned into a bevy prototype: https://github.com/NexusSocial/skilltree/pull/23
I'm using `egui_wgpu` still, but I saw that `bevy_egui` uses bevy directly.

Putting aside for a moment the question of how to handle input, do you think its wiser to integrate with this plugin and use bevy directly, or for me to make a separate plugin and double down on `egui_wgpu`?

**Comment by mvlabat** [comment]
Wow, that's awesome progress!

> Putting aside for a moment the question of how to handle input, do you think its wiser to integrate with this plugin and use bevy directly

I don't have any good arguments atm, but intuitively I think it would be better to build this with Bevy abstractions if possible.

> If I try to make a PR, how much bandwidth do you have for coaching me?

I'll do my best to review it at soon as possible, not so sure on coaching though :( I'm re-learning rendering almost from scratch each time I touch it, lol, as I don't do it too often. But I'm sure there are many folks in the Bevy discord who will be willing to assist.

**Comment by afpro** [comment]
Any progress buddy? I'm not very familiar with egui and wgpu, but maybe I can do something if you already have a PR.

**Comment by mvlabat** [comment]
Rendering UI to worldspace should now be possible (we still lack a proper input handling though, I'll probably fix this once Bevy 0.15 lands).
