### ISSUE TITLE
Upgrade to egui 0.23

### ISSUE THREAD

**Issue by naomijub** [mvlabat/bevy_egui#215]
Hi, I'm trying to access my UI as a `Res`/`ResMut`, but the current implementation is not `Send`. This was fixed in egui side in version 0.23 https://github.com/emilk/egui/issues/3148. Can you please upgrade egui?

**Comment by zicklag** [comment]
I'm going to take a look at this. I need it for the new keyboard navigation feature.

**Comment by naomijub** [comment]
Awesome, thanks
