### ISSUE TITLE
Compile Errors with bevy_dylib on Windows10 - rust-lld: error: too many exported symbols (max 65535)

### ISSUE THREAD

**Issue by bayswaterpc** [mvlabat/bevy_egui#22]
I'm trying to get the bevy dynamic building feature working for faster build times.  I have been able to get the bevy crate's examples building with the dynamic feature , so I know it is possible for bevy to build with dynamic on my machine with the following these steps

https://github.com/bevyengine/bevy/issues/1126
https://bevyengine.org/learn/book/getting-started/setup/ - Fast Compile section

However, the bevy_egui is not working with those same steps.  It does work with the dynamic feature removed. I've created a fork showing the changes I've made, just adding the fast compile .carg/config.toml file & "dynamic" feature to bevy dependency.

https://github.com/bayswaterpc/bevy_egui

It gives the following error when building any of the example targets
[bevy_egui dynamic bevy error blob.txt](https://github.com/mvlabat/bevy_egui/files/6412088/bevy_egui.dynamic.bevy.error.blob.txt)

If anyone has been able to get this working on Windows would love some tips.

**Comment by bayswaterpc** [comment]
Posted this a second too soon, did more digging saw the following advice on this thread and got it working
https://github.com/bevyengine/bevy/pull/2016

Will make a pull request for this

**Comment by inodentry** [comment]
I am getting this error even on stable rust, which doesn't have the `-Zshare-generics` option. Hence, the advice given before for fixing the issue, does not actually fix the issue.

This is without even any plugins. I simply cloned the latest bevy main `dbd856de` and did:
```
cargo build --example load_gltf --features dynamic
```

It fails to link with the error:
```
  = note: rust-lld: error: too many exported symbols (max 65535)
```
