### ISSUE TITLE
How to center?

### ISSUE THREAD

**Issue by meanbeanmachine** [mvlabat/bevy_egui#222]
Shouldn't the following code center the widgets in the middle of the screen?  Depending on the horiz/vert order, the two elements are either at the top of the screen or on the far left of the screen... never center.

![Screenshot from 2023-11-05 11-18-51](https://github.com/mvlabat/bevy_egui/assets/29932473/7a0ceb1b-b353-41d5-8c0b-26e1fc14c4b3)
![Screenshot from 2023-11-05 11-19-44](https://github.com/mvlabat/bevy_egui/assets/29932473/bc4839cb-e719-4d98-b2f4-75ba335055fd)

```fn error(
    mut ctx: EguiContexts,
    mut exit: EventWriter<WindowCloseRequested>,
    error: Res<AppError>,
    window: Query<Entity, With<Window>>,
) {
    egui::CentralPanel::default().show(ctx.ctx_mut(), |ui| {
        ui.horizontal_centered(|ui| {
            ui.vertical_centered(|ui| {
                ui.label(error.0.to_string());
                if ui.button("Exit").clicked() {
                    exit.send(WindowCloseRequested {
                        window: window.single(),
                    });
                }
            });
        });
    });
}```

**Comment by mvlabat** [comment]
Sorry, I didn't notice the issue in time. Not sure if it's still actual, in any case, it's a question about `egui` itself. I unfortunately don't know a quick answer for it either, so it's best to ask in their repo/discord.
