### ISSUE TITLE
Sticky shift key

### ISSUE THREAD

**Issue by doonv** [mvlabat/bevy_egui#232]
## The bug

Pressing the <kbd>Shift</kbd> key once causes it to remain pressed after releasing it. This usually doesn't affect anything but it does effect `ScrollArea` scrolling, which forces horizontal scrolling after <kbd>Shift</kbd> was pressed.

## Example

```rs
use bevy::prelude::*;
use bevy_egui::{egui, EguiContexts, EguiPlugin};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(EguiPlugin)
        // Systems that create Egui widgets should be run during the `CoreSet::Update` set,
        // or after the `EguiSet::BeginFrame` system (which belongs to the `CoreSet::PreUpdate` set).
        .add_systems(Update, ui_example_system)
        .run();
}

fn ui_example_system(mut contexts: EguiContexts) {
    egui::Window::new("Hello").show(contexts.ctx_mut(), |ui| {
        let pressed = ui.input(|i| i.modifiers.shift);
        info!("pressed? {pressed}");
        ui.label("world");
    });
}
```

It will start out printing `pressed? false`. But after tapping <kbd>Shift</kbd> it will only print `pressed? true`

**Comment by doonv** [comment]
Wait no it looks like it's a bevy problem?

**Comment by doonv** [comment]
Yeah it's a bevy problem. Should be fixed by https://github.com/bevyengine/bevy/pull/10702.

**Comment by SludgePhD** [comment]
I opened a PR with a fix in https://github.com/mvlabat/bevy_egui/pull/298
