### ISSUE TITLE
Pressing Enter in a TextEdit with `prevent_default_event_handling: false` inputs an "E"

### ISSUE THREAD

**Issue by aecsocket** [mvlabat/bevy_egui#235]
Reproduction: https://github.com/aecsocket/bevy-egui-enter-bug

`cargo run --target wasm32-unknown-unknown`

```rs
fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins.set(WindowPlugin {
                primary_window: Some(Window {
                    prevent_default_event_handling: false,
                    ..default()
                }),
                ..default()
            }),
            EguiPlugin,
        ))
        .add_systems(Update, ui)
        .run();
}
// ...
fn ui(mut egui: EguiContexts, mut text: ResMut<Text>) {
    egui::Window::new("Window").show(egui.ctx_mut(), |ui| {
        ui.add(egui::TextEdit::singleline(&mut text.0));
    });
}
```

This is probably a bug in an upstream dependency (maybe winit? egui?), but I'm not experienced enough with this stuff to know exactly which dependency is causing it.

https://github.com/mvlabat/bevy_egui/assets/43144841/96bbd067-6670-4234-a59a-0a4890904754

**Comment by mvlabat** [comment]
I believe this is no longer actual with the newer version of `winit`. But please let me know if it's still is.
