### ISSUE TITLE
How to scale the ui globally?

### ISSUE THREAD

**Issue by jan-tennert** [mvlabat/bevy_egui#244]
Hey, in egui you can change the global `zoom_factor` or `pixels_per_point` and I tried to do this in bevy_egui like this:
```kotlin
if keys.pressed(KeyCode::ControlLeft) && keys.just_pressed(KeyCode::Plus) {
    let ctx = egui_context.ctx_mut();
    ctx.set_zoom_factor(ctx.zoom_factor() * 1.1);
} else if keys.pressed(KeyCode::ControlLeft) && keys.just_pressed(KeyCode::Minus) {
    let ctx = egui_context.ctx_mut();
    ctx.set_zoom_factor(ctx.zoom_factor() * 0.9);
}
```
However the ui changes for like 0.5 seconds and then flips back. What am I doing wrong?

**Comment by jan-tennert** [comment]
Nvm found out about `EguiSettings`

**Comment by mvlabat** [comment]
Yeah, one of the ways is to do that with `EguiSettings`, but it was introduced before Egui had its own scale factor. It should work as well, so I'll double-check it too.
