### ISSUE TITLE
`RenderGraphConfig` is unused

### ISSUE THREAD

**Issue by spectria-limina** [mvlabat/bevy_egui#254]
Coming from investigating #112, the thread mentions `RenderGraphConfig` providing information about the render pass used by egui, but as far as I can tell it's never actually installed into the `World` or indeed constructed at all.

**Comment by mvlabat** [comment]
Hey, thanks for calling this out. I don't have a solution for #112 yet, though I'm happy to merge a PR if someone wants to implement it. For now, I'll just remove the struct to avoid the confusion.

**Comment by mvlabat** [comment]
Removed in 0.27
