### ISSUE TITLE
Runtime Error on examples as Main Windows10

### ISSUE THREAD

**Issue by jmw992** [mvlabat/bevy_egui#26]
I cloned the crate and I can run the examples from the command line fine. ex `cargo run --example simple`

If I make a main.rs and fill it with the contents of simple.rs and `cargo run` it will fail with a runtime error and a gnarly error 
```
thread 'thread 'thread 'mainCompute Task Pool (5)Compute Task Pool (2)' panicked at '' panicked at '' panicked at 'Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', ', ', C:\Users\jmw99\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\system\system_param.rsC:\Users\jmw99\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\system\system_param.rsC:\Users\jmw99\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\system\system_param.rs:::244244244:::171717
```

and it's full backtrace [simple backtrace.txt](https://github.com/mvlabat/bevy_egui/files/6455942/simple.backtrace.txt)

I am using windows 10, is there any special configuration I have to do in the TOML?  It clearly can work as it runs from the example configurations no problem.  Thanks

**Comment by mvlabat** [comment]
Hey @jmw992! Have you got Bevy specified in your dependencies? It looks like your project uses Bevy without the features that define graphics backend, which is I guess what you would get if you specified only bevy_egui in Cargo.toml
