### ISSUE TITLE
Mouse up events are ignored on native if cursor moves to another window in between.

### ISSUE THREAD

**Issue by jakobhellermann** [mvlabat/bevy_egui#272]
When you mousedown on a window, drag outside of it and release, the press state in egui is cleared correctly (at least on native, in browsers this doesn't seem to work https://github.com/mvlabat/bevy_egui/issues/101).

But when you mousedown on window A, drag over to window B, release, then the state is kept until you click in window A again.

Here's an example, printing
```rs
println!("Window 1 (or 2) {:?}", ui.input(|input| input.pointer.press_origin()));
```
in `two_windows.rs`:

https://github.com/mvlabat/bevy_egui/assets/22177966/a3c297d7-4d57-48b4-a226-343c1469f93e

**Comment by mvlabat** [comment]
Hey! Thanks for the report. I'll check if we can fix this

**Comment by mvlabat** [comment]
#273 should fix this
