### ISSUE TITLE
Support epaint::Shape::Callback(PaintCallback)

### ISSUE THREAD

**Issue by PPakalns** [mvlabat/bevy_egui#294]
https://github.com/mvlabat/bevy_egui/blob/6705757bc29f7194e58129276100a4d52b93aadc/src/egui_node.rs#L222

PaintCallback is not supported. This callback allows painting 3D views, visualizations, etc inside egui Windows using underlying backend (bevy rendering / wgpu). 

Maybe PaintCallback could somehow get expanded into render graph subgraph.
https://docs.rs/bevy_render/latest/bevy_render/render_graph/struct.RenderGraph.html#method.add_sub_graph

**Comment by mvlabat** [comment]
I'm happy to accept a PR implementing this. Unfortunately, I don't have enough capacity to work on this myself.
