### ISSUE TITLE
Consuming input events

### ISSUE THREAD

**Issue by Bauxitedev** [mvlabat/bevy_egui#31]
This isn't really an issue, more of a question... I was wondering, it is possible to check if any GUI elements from egui consumed an input event? Basically, I want to avoid getting input events in my own entities if the user e.g. clicked on a gui element, so I don't get the mouse events twice. (e.g. in a FPS game if you click the "pause" button, it shouldn't shoot the gun, because the GUI should've already consumed the input event)

**Comment by OfficialURL** [comment]
Perhaps [`wants_pointer_input`](https://docs.rs/egui/0.12.0/egui/struct.Context.html#method.wants_pointer_input) is what you want?

**Comment by Bauxitedev** [comment]
> 
> 
> Perhaps [`wants_pointer_input`](https://docs.rs/egui/0.12.0/egui/struct.Context.html#method.wants_pointer_input) is what you want?

That did the trick, thanks!
