### ISSUE TITLE
Holding arrow keys in text panel does not keep moving cursor.  

### ISSUE THREAD

**Issue by ralfbiedert** [mvlabat/bevy_egui#36]
### Summary

Holding an arrow key, both in the `ui` example, and in my project, does not keep moving the cursor inside `ui.text_edit_singleline` elements.

In the official [egui demo app](https://github.com/emilk/egui/tree/master/egui_demo_app) this works.

### How to Reproduce

- `cargo run --example ui` 
- Click the "Write something" panel on the left; hold `a`, observe production of `aaaaaaaaaaaaaaaaa`
- While still in panel, hold `Arrow left`. The cursor will only jump one character left.

**Comment by mvlabat** [comment]
Hi! Thanks for creating the issue and sorry it took me a while to respond. This should be fixed in 0.6.2.

**Comment by ralfbiedert** [comment]
Yes, can confirm. Thanks a lot!
