### ISSUE TITLE
Checking if keyboard/mouse event was/should be handled by egui

### ISSUE THREAD

**Issue by tanner-bruce** [mvlabat/bevy_egui#40]
Is there a way to check if egui is handling the currently received input event? I'm trying to add hotkeys but need to know first if the UI should be handling the event or if I should handle it in the game. I think I could basically check if any text input has focus, but it seems like there should be a better way

**Comment by mvlabat** [comment]
Hi @tanner-bruce! There sure is: you can use `Context::wants_keyboard_input` and `Context::is_using_pointer`. Let me know if that helps!

**Comment by tanner-bruce** [comment]
Thanks! Can't believe I didn't see these 🤦, they did the trick
