### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by zeroeightysix** [mvlabat/bevy_egui#54]
Both `bevy` and `winit` support wayland surfaces natively, but `bevy_egui` opts out of the necessary feature flags.

In testing, it looks like just enabling them works fine. I don't know how to test if it makes a difference on wasm, though. Consider enabling `wayland` for bevy and winit, or at least supporting this through a feature flag?

**Comment by mvlabat** [comment]
I believe that just enabling `wayland` feature for `bevy` in the project that depends on both `bevy` and `bevy_egui` will do it. Cargo features are supposed to be additive, so even though `bevy_egui` just specifies the minimal feature set it needs, your final binary will have Bevy compiled with a union of features specified in your `Cargo.toml` and `bevy_egui`'s one.
Unless `bevy_egui` itself needs any API that is exposed by `wayland` feature, there shouldn't be a need for enabling it.

Let me know if that helps.

**Comment by mvlabat** [comment]
I'll close the issue as I believe there isn't anything incompatible with Wayland in `bevy_egui`. If the problem still persists and you can confirm that it's indeed a problem on `bevy_egui`'s side, please let me know or feel free to open a new issue.
