### ISSUE TITLE
Can't run egui system in `CoreStage::PostUpdate`: 'already mutably borrowed',

### ISSUE THREAD

**Issue by ndarilek** [mvlabat/bevy_egui#55]
Hello,

Hit this one in the process of porting my game to Bevy 0.6. I have an egui system that needs to access `context.ctx().output().events` in `CoreSystem::PostUpdate`. This was doable in 0.5, but in 0.6 gives:

```
thread 'Compute Task Pool (1)' panicked at 'already mutably borrowed', C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\atomic_refcell-0.1.8\src\lib.rs:151:23                                                                         
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                        
```

I can send you the full stacktrace if you like, but I do have a sample that reproduces this. https://github.com/ndarilek/bevy_egui_a11y has a main branch that works against Bevy 0.5, and a bevy-0.6 branch that crashes immediately on launch.

I tried moving this system around a bit, but it really needs to run with these events populated, and none of the simpler stage moves (I.e. just running it in Update or PreUpdate) did anything other than prevent the crash. I suppose I could manually order each UI system to run before the screen reader, but that'd be a lot of code on each system when what I really want to do is add the screen reader before whatever egui needs to do to clean up the context.

Any idea why this stopped working? Are borrows handled differently in 0.9 and 0.10 in some way that might account for this?

Thanks a bunch!

**Comment by mvlabat** [comment]
Oh, I initially assumed that the problem was related to some of the stages that we removed during the Bevy 0.6 upgrade. But it looks like you're just missing `ResMut<EguiContext>` (instead of `Res`) in your systems.

From the readme:
```
// Note the usage of `ResMut`. Even though `ctx` method doesn't require
// mutability, accessing the context from different threads will result
// into panic if you don't enable `egui/multi_threaded` feature.
fn ui_example(egui_context: ResMut<EguiContext>) {
    egui::Window::new("Hello").show(egui_context.ctx(), |ui| {
        ui.label("world");
    });
}
```

I wasn't able to confirm this as `bevy_tts` doesn't seem to compile on the 0.6 branch but I think it should do the trick. Let me know if this helps!

**Comment by ndarilek** [comment]
Got it, thanks. This cleared the panic for me. It introduces what I assume are system ordering issues sometimes, but those are separate issues and I'll open another if I can't fix it on my end.
