### ISSUE TITLE
How to achieve full screen on the web?

### ISSUE THREAD

**Issue by imxood** [mvlabat/bevy_egui#56]

**Comment by mvlabat** [comment]
Hi! I've never done it myself but have you tried configuring your screen with [`WindowMode::Fullscreen`](https://docs.rs/bevy_window/latest/bevy_window/enum.WindowMode.html#variant.Fullscreen). I don't know whether it's supported in browsers or not though. Anyway, it seems like this question is related to Bevy itself, so I think you can find more help in [its repository](https://github.com/bevyengine/bevy/discussions) or [Discord](https://discord.gg/bevy).

Let me know if there's anything that you believe `bevy_egui` can assist with for fullscreen windows.

**Comment by imxood** [comment]
@mvlabat The problem is fixed, now the problem is on winit. In bevy, there is also this problem. In winit, the window in the web represents a canvas instance, and winit does not manage the Window object. When the Window changes, winit cannot know it. So I used web_sys to monitor the resize event of the Window by myself. A system is added to bevy to handle the resize event of Window, and change the size of the canvas when the resize event of Window occurs. Also, at the beginning, use the width and height of the Window to set the size of the canvas. 

Also, on the web, winit handles WindowDescriptor.mode badly!

**Comment by imxood** [comment]
Here is my key code:
```rust
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};

use bevy::prelude::*;
use wasm_bindgen::{prelude::*, JsCast};

pub struct WebPlugin;

impl Plugin for WebPlugin {
    fn build(&self, app: &mut App) {
        // window resize event flag
        let window_resize_evt = WindowResizeEvent::default();

        let mut window_resize_evt0 = window_resize_evt.clone();

        // 用于处理 Window 的 resize event
        let window_resize_handle = WindowResizeHandle {
            listener: Closure::wrap(Box::new(move || {
                window_resize_evt0.set();
                log::info!("resize!");
            }) as Box<dyn FnMut()>),
        };

        app.insert_resource(window_resize_evt);
        app.insert_resource(window_resize_handle);
        app.add_startup_system(window_maxium);
        app.add_startup_system(window_resize_register);
        app.add_system(window_resize_nofity);
    }
}

// 初始化时, 设置canvas最大化
fn window_maxium(mut windows: ResMut<Windows>) {
    let window = web_sys::window().expect("no global `window` exists");
    let width: f32 = window.inner_width().unwrap().as_f64().unwrap() as f32;
    let height: f32 = window.inner_height().unwrap().as_f64().unwrap() as f32;
    if let Some(window) = windows.get_primary_mut() {
        window.set_resolution(width, height);
        log::info!("set_resolution({width}, {height})");
    }
}

/// 注册 Window 的 resize事件
fn window_resize_register(window_resize_handle: Res<WindowResizeHandle<dyn FnMut()>>) {
    let window = web_sys::window().expect("Failed to obtain window");
    window.set_onresize(Some(window_resize_handle.listener.as_ref().unchecked_ref()));
}

fn window_resize_nofity(
    mut window_resize_evt: ResMut<WindowResizeEvent>,
    windows: ResMut<Windows>,
) {
    if window_resize_evt.get() {
        window_maxium(windows);
        window_resize_evt.clear();
    }
}

pub struct WindowResizeHandle<T: ?Sized> {
    pub listener: Closure<T>,
}

unsafe impl<T: ?Sized> Send for WindowResizeHandle<T> {}
unsafe impl<T: ?Sized> Sync for WindowResizeHandle<T> {}

#[derive(Default, Clone)]
pub struct WindowResizeEvent {
    happened: Arc<AtomicBool>,
}

impl WindowResizeEvent {
    pub fn set(&mut self) {
        self.happened.store(true, Ordering::SeqCst);
    }
    pub fn clear(&mut self) {
        self.happened.store(false, Ordering::SeqCst);
    }
    pub fn get(&mut self) -> bool {
        self.happened.load(Ordering::SeqCst)
    }
}
```

**Comment by imxood** [comment]
![image](https://user-images.githubusercontent.com/14890680/149654727-e779e5fe-9514-4289-bfbc-72bf00d5ca84.png)

**Comment by mvlabat** [comment]
Oh, I assumed you needed a real fullscreen mode (like on youtube).

Thanks for sharing your example of how you were able to accomplish this.

This is how I also resize the canvas in my pet project (it's not yet updated to Bevy 0.6 though, I don't know if anything's changed in this regard): https://github.com/mvlabat/muddle-run/blob/fbdba0ce0e32ef1b7763be568b910b499bdd70f6/bins/web_client/src/lib.rs#L15
It seems like it didn't require setting a window resolution manually. But, as I said, it might be outdated.
