### ISSUE TITLE
Internal handling of texture ids

### ISSUE THREAD

**Issue by pubrrr** [mvlabat/bevy_egui#65]
I have a dynamic number of images I want to show using bevy_egui. I am trying to preview single frames of animations. I basically have a `handles: Vec<Handle<Image>>`. To display that with bevy_egui, I figured I have to do something like

```
for (index, handle) in handles {
    egui_context.set_egui_texture(index as u64, handle)
}
```

However, If I try to do that with my next animation, the texture ids are already occupied by the previous animation. Thus I would need to have my program remember the texture ids already in use.

Could `EguiContext` do that internally for me? I imagine a function like
```
impl EguiContext {
    /// looks for the next free id and returns the TextureId that you can directly use with Ui::image
    pub fn add_texture(&mut self, texture: Handle<Image>) -> TextureId;
}
```

Benefits:
* The consumer does not need to remember occupied ids. (`EguiContext` does that implicitly already anway.)
* The consumer does not need to know how to generate `TextureId`s. It would be similar to Bevy's `Handle`s: I can ask bevy_egui to take care of an image, I get the id and can use it without ever looking into it.

**Comment by pubrrr** [comment]
Another benefit probably: Adding the same `Handle` a second time could be recognized and ignored handing out the same `TextureId` again.

**Comment by TheDestroyer19** [comment]
There's a bigger benefit - libraries which use bevy_egui (such as bevy_inspector_egui) become much more composable.
Right now, to avoid conflicts with bevy_inspector_egui I have to use it's method of generating indexes - which isn't documented.

**Comment by mvlabat** [comment]
Hi! Sorry for ignoring the issue for so long.

I think I can add something like that.

I believe it'll force the following change upon the users that want to render just a fixed set of images: instead of using a constant and correlating it to a texture id, they'll have to create an additional resource that would store ids, add it as a dependency to at least two systems (a startup system and a system where actual rendering happens).

```rust
struct TextureIds {
    icon: u64,
}

fn load_assets(mut egui_context: ResMut<EguiContext>, assets: Res<AssetServer>, mut texture_ids: ResMut<TextureIds>) {
    texture_ids.icon = egui_context.add_texture(assets.load("icon.png"));
}

fn ui_example(
    mut egui_ctx: ResMut<EguiContext>,
    texture_ids: Res<TextureIds>,
) {
    egui::SidePanel::left("side_panel")
        .default_width(200.0)
        .show(egui_ctx.ctx_mut(), |ui| {
            ui.add(egui::widgets::Image::new(
                egui::TextureId::User(texture_ids.icon),
                [256.0, 256.0],
            ));
        });
}
```

But I guess the benefits are worth it.

**Comment by mvlabat** [comment]
Another thing that I'm considering: is it worth keeping `set_egui_texture` to be able to re-use ids by swapping images? Maybe this functionality could be exposed via something like `replace_image(existing_image: Handle<Image>, new_image: Handle<Image>) -> bool`, but I'm not sure whether it's something that users would care about.

@jakobhellermann I would also love to hear your perspective on the suggestion to replace `set_egui_texture` with `add_texture`. AFAIK, as long as `add_texture` returns consistent ids for the same images, it should be fine for the inspector lib. The only possible issue that I can see with this is the fact that `add_texture` will be impossible to use to retrieve texture ids when the context is already borrowed. But this should be easy to workaround.

**Comment by pubrrr** [comment]
> Another thing that I'm considering: is it worth keeping `set_egui_texture` to be able to re-use ids by swapping images? Maybe, instead of `set_egui_texture`, this functionality can be exposed with something like `replace_image(existing_image: Handle<Image>, new_image: Handle<Image>) -> bool`, but I'm not sure whether it's something that users would care about.
> 
> @jakobhellermann I would also love to hear your perspective on the suggestion to replace `set_egui_texture` with `add_texture`. AFAIK, as long as `add_texture` returns consistent ids for the same images, it should be fine for the inspector lib. The only possible issue that I can see with this is the fact that `add_texture` will be impossible to use to retrieve texture ids when the context is already borrowed. But this should be easy to workaround.

To me it seems, that a user should use either or - but never both. If he does, things get weird, because he could accidentally overwrite an id that was set previously internally. I don't know whether it's a good idea to offer both...
