### ISSUE TITLE
Clipboard dependency unmaintained

### ISSUE THREAD

**Issue by Shatur** [mvlabat/bevy_egui#67]
This crate depends on https://github.com/aweinstock314/rust-clipboard which is unmaintained. Which also depends on https://github.com/quininer/x11-clipboard/issues/19 that unmaintained to. Which also depends on xkb which is [unsound and also unmaintained](https://github.com/RustSec/advisory-db/issues/653) :rofl:
Can we switch to a different crate for clipboard management?

**Comment by mvlabat** [comment]
Hi! I'm glad to replace it with something else, I just haven't found any suitable alternative. Any ideas for the replacement? Or maybe we'll end up implementing the functionality ourselves :)

**Comment by Shatur** [comment]
@mvlabat I looked for libraries and found only three options:
1. https://github.com/ArturKovacs/arboard. It's already much better then `clipboard`, but the author is [looking for a maintainer](https://github.com/ArturKovacs/arboard/issues/26). We could switch to it in a short term, the author is active, pretty sure the maintainer will appear.
1. https://github.com/hecrj/window_clipboard. Experimental, but active :)
1. There is a fork of `clipboard` crate that we use: https://github.com/mcobzarenco/crossclip. It's maintained, but it still uses `x11-clipboard` that I mentioned in the first message. So the solution could be switch to this fork and send a PR with a replacement for `x11-clipboard`. I found only this crate: https://crates.io/crates/clipboard_x11 (it's from the repo I linked in 2.)

**Comment by mvlabat** [comment]
@Shatur thank you a lot for the research! I've just pushed a PR switching to `arboard` (#72), and it looks pretty good. Feel free to review and leave any comments there, I'll also be glad to have people testing it on different platforms.

I'm planning to release it with the next Egui upgrade, including it into the next minor release.
