### ISSUE TITLE
how to change the logo color

### ISSUE THREAD

**Issue by pyweeker** [mvlabat/bevy_egui#69]
Hello, i see how to load and remove the bevy logo picture.
What i'd like to do is to send signal to change the logo teint / color , but keep the texture.

The dirty solution is to have many png similar but with preprocessed colors and to load it when needed.

The wished solution would be to have buttons to increment/decrement RGBA canals, and to get fast changing colors on the left side panel. Is there a struct field or method to target the color inside egui part ?
The bevy part is SpriteBundle.sprite.color

What i thought is to access through a Component like this:
```
#[derive(Component)]
struct CurrentColorIndicator;
```

but here  :   

```
egui::SidePanel::left("side_panel")
        .default_width(100.0)
        .show(egui_ctx.ctx(), |ui| {
            ui.heading("Side Panel");            

            ui.add(egui::widgets::Image::new(
                egui::TextureId::User(BEVY_TEXTURE_ID),
                [256.0, 256.0],
            ));
        .insert(CurrentColorIndicator)
```

i can not do
.insert(CurrentColorIndicator)

**Comment by mvlabat** [comment]
Hi there!

I'm not sure this is something I'll implement in the library unless it's a popular request. Adding tint support would require passing this with the vertex data and modifying shaders, which I'd like to avoid if it's a feature that will be unused in 99.9% of cases. But, again, if more users will ask for this feature, I might reconsider it.

To avoid pre-generating images on CPU, I'd look into rendering to a texture (related issue: #9) and then rendering it as an image via Egui. To be fair, this is something I don't know how to achieve yet myself, and this Bevy PR suggests it's not even possible atm: https://github.com/bevyengine/bevy/pull/3412. But when it becomes possible, I'll try to add an example to this repo.

**Comment by pyweeker** [comment]
Hi !
i thought it was already implemented and straight forward !

**Comment by mvlabat** [comment]
I'm closing the issue as it's not something I currently see as a part of `bevy_egui`.
