### ISSUE TITLE
UI elements cannot keep focus if system is on main thread.

### ISSUE THREAD

**Issue by Dzejkop** [mvlabat/bevy_egui#70]
In order to be able to open a native file dialog (I used the `native-dialog` crate) I had to put the ui system on the main thread.

The reason being that on Mac, opening the file dialog is only supported from the main thread.

When the ui system is used in a `single_threaded` system stage it keeps on losing focus from all widgets.

https://user-images.githubusercontent.com/5088647/154774710-e3b149fc-b724-4a15-a1c2-a9f1becc88ef.mov

Minimal reproduction code:
`src/main.rs`:
```rust
use bevy::prelude::*;
use bevy_egui::{egui, EguiContext, EguiPlugin};

#[derive(Debug, Hash, PartialEq, Eq)]
pub struct MainThread;

impl StageLabel for MainThread {
    fn dyn_clone(&self) -> Box<dyn StageLabel> {
        Box::new(MainThread)
    }
}

fn main() {
    App::new()
        .add_stage(MainThread, SystemStage::single_threaded())
        .add_plugins(DefaultPlugins)
        .add_plugin(EguiPlugin)
        .add_system_to_stage(MainThread, ui_system) // <- focus will be lost
        // .add_system(ui_system) // <- focus works fine
        .run();
}

fn ui_system(mut egui_context: ResMut<EguiContext>) {
    egui::Window::new("Whatever").show(egui_context.ctx_mut(), |ui| {
        ui.text_edit_singleline(&mut String::from("Hello, World!"));
    });
}

```

`Cargo.toml`:
```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6.1" }
bevy_egui = "0.11.1"
```

**Comment by mvlabat** [comment]
Hi! Thanks for creating the issue.

The problem is that when you do `add_stage`, I believe it adds a stage to the end of the schedule. If you change that line to `.add_stage_before(CoreStage::PostUpdate, MainThread, SystemStage::single_threaded())`, it'll stop losing the focus.

**Comment by mvlabat** [comment]
I've just pushed a commit clarifying this bit in the docs: f6fa095f24f4f0d365880353828692fc3025a57c

**Comment by Dzejkop** [comment]
Ok, thanks!
