### ISSUE TITLE
Resource requested by bevy_egui::systems::init_contexts_on_startup does not exist

### ISSUE THREAD

**Issue by chungquantin** [mvlabat/bevy_egui#77]
After the initialization of the bevy app, I run `cargo run` with the `WorldInspectorPlugin` but encounter this error.

**Comment by chungquantin** [comment]
thread 'Compute Task Pool (3)' panicked at 'Resource requested by bevy_egui::systems::init_contexts_on_startup does not exist: bevy_window::windows::Windows
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mvlabat** [comment]
Hi @chungquantin. I think you're missing `.add_plugins(DefaultPlugins)` in the code that builds your app.

**Comment by mvlabat** [comment]
I'll close the issue. If it still persists, feel free to answer here in the comments or open a new one.
