### ISSUE TITLE
Possible to render to world space rather than screen space?

### ISSUE THREAD

**Issue by deontologician** [mvlabat/bevy_egui#86]
I'd like to render some egui windows relative to the world rather than the window. Is this possible?

If not, could you sketch out what might need to be done /changed to add this feature? I would be willing to submit a PR for it

**Comment by mvlabat** [comment]
Hi! No, it's not possible atm, but it's definitely a feature I'd like to see in `bevy_egui`. I think there are the following major puzzles missing in the plugin:
- Being able to draw into a texture. This should be a good example to check: https://github.com/bevyengine/bevy/blob/main/examples/3d/render_to_texture.rs.
- Providing a way for users to overwrite or set a pointer position manually (the system to look into is `process_input`).

**Comment by aevyrie** [comment]
You can do this now using the built in bevy `world_to_screen` utility function. We do this to pin labels to objects in the world, by converting their `GlobalTransform` to screen space, and using that to place the window.

**Comment by mvlabat** [comment]
I assume this answers the question so I'll close the issue. But feel free to comment or open a new one if you have any questions remaining.
