### ISSUE TITLE
UI not rendering

### ISSUE THREAD

**Issue by BrettWitty** [mvlabat/bevy_egui#87]
I recently updated `bevy_egui` to 0.12.1 (from 0.11) and `bevy-inspector-egui` to 0.9 (from 0.8). Both are now using `egui` 0.17, as checked via `cargo tree`.

Code that previously rendered fine does nothing. It runs (evidenced by debugging print statements inside a `Window::new("").show()` function. All the bevy systems are still running, but the `egui` code yields nothing.

There are no errors in compilation, no panics.

Perhaps an issue with providing the right contexts/data for bevy and egui in #78 ?

**Comment by mvlabat** [comment]
Hi! Any chance I could take a look at the project you're having the issue with or a minimal reproducible example?

**Comment by BrettWitty** [comment]
My project is a bit complicated, but I managed to make a MRE: https://gist.github.com/BrettWitty/8887a4d2405eafe5343f00d9dcdb41f9

**Comment by BrettWitty** [comment]
If I change `bevy_egui` to 0.11 in my `Cargo.toml` (and not touch the `bevy-inspector-egui` version), it runs as expected.

**Comment by mvlabat** [comment]
Oh, I see. You should either remove `.add_plugin(EguiPlugin)` or move it above `.add_plugin(WorldInspectorPlugin::new())`. `bevy-inspector-egui` initialises `bevy_egui` itself if it hasn't been added. But if you add it once more, that'll break things.

**Comment by BrettWitty** [comment]
Ah that's great. Thanks for solving it.
