### ISSUE TITLE
Bevy render to texture

### ISSUE THREAD

**Issue by samsamai** [mvlabat/bevy_egui#9]
Please excuse this non-issue, just looking for some help.
I'm looking to render a 3D scene with bevy and show it in a egui window as an image, the bevy_gui example is very close to what I want. I was wondering if you had any pointers or examples of how to render to a texture instead of the screen in bevy.

**Comment by mvlabat** [comment]
Hi! No problem, I think this actually a good use-case to explore.

I believe you can find several useful examples of rendering something to a texture in this thread: https://github.com/bevyengine/bevy/issues/1207

Here's one of them: https://github.com/mrk-its/bevy/blob/29fe738daeb05165ee6459a87b72c7c0f2699109/examples/3d/render_to_texture.rs

And I believe this is a live version of it: https://mrk.sed.pl/bevy-showcase/#render_to_texture

I think this is already achievable with `bevy_egui`, but I'm not sure how optimal it is at the moment. You'd need to create a texture node, which would be used for rendering a scene into it, and you'd pass the related texture handle to `set_egui_texture`. But I'm afraid that would involve reading data from GPU to RAM, doing several copies, which is somewhat inefficient.

I'd like to learn how to avoid that, and probably there's something that we could provide via `bevy_egui` interface to pass device textures directly.

**Comment by samsamai** [comment]
Thanks @mvlabat  for the link to the source of that example, that will be very helpful. I'll see if I can get it working with bevy_egui.

**Comment by mvlabat** [comment]
Sure. :) Let me know if you get any results. I've also created an issue to track the feature that would provide an optimal way of rendering such a texture inside of bevy_egui widgets: #11.
