### ISSUE TITLE
Provide ability to use GIT egui

### ISSUE THREAD

**Issue by justacec** [mvlabat/bevy_egui#91]
I have a situation where I would like to use a Table widget.  This is not built into the released version of egui right now, but seems as though a recent merge to master has provided some basic functionality.  Is there a way (without forking bevy_egui) that I can get bevy_egui to use the GIT version of egui?  Right now it seems as though it is hard coded.

See discussion at https://github.com/emilk/egui/issues/296 and https://github.com/emilk/egui/pull/963 for more details.

Possibly adding a feature flag for a specific git branch of egui would be nice.

**Comment by mvlabat** [comment]
Hi @justacec! I haven't looked into the most recent Egui changes in git yet, but there's a chance that the current version of `bevy_egui` is compatible with it. To make your project use the git version, you can put the following into your `Cargo.toml`:

```toml
egui = { git = "https://github.com/emilk/egui.git" }
```

Let me know if that works!

**Comment by justacec** [comment]
Humm.  Looks like it did not work:

```
bash-3.2$ cargo build
    Updating git repository `https://github.com/emilk/egui.git`
error: failed to select a version for `egui`.
    ... required by package `bevy_egui v0.13.0`
    ... which satisfies dependency `bevy_egui = "^0.13"` (locked to 0.13.0) of package `FirmwareClient v0.1.0 (/Users/justaceclutter/Desktop/Topics/RocketTracker/FirmwareClient)`
versions that meet the requirements `^0.17` (locked to 0.17.0) are: 0.17.0

the package `bevy_egui` depends on `egui`, with features: `convert_bytemuck` but `egui` does not have these features.
```

Seems that the `egui` author refactored the crates features and changed `convert_bytemuck` to just `bytemuck`.

**Comment by mvlabat** [comment]
I tried to make a quick upgrade to the git version but stumbled upon some other breaking changes and new features that aren't quite trivial to implement. Unfortunately, I don't have enough time to work on that at the moment. But I'll try my best to release a new version of bevy_egui as soon as the new version of Egui lands on crates.io.

**Comment by justacec** [comment]
:). Thanks for looking into it.  It's ok.  I have things working as of now.  But not with GIT bevy.  

No need to change up your flow for me.  :)

**Comment by mvlabat** [comment]
Ok, I figured I won't include `PaintCallback` support in the release, as I have no idea how to make it work with Bevy. Here's the branch supporting the new version: https://github.com/mvlabat/bevy_egui/pull/99

**Comment by justacec** [comment]
Just got done making the adjustments in my Cargo.toml file:

```
bevy_egui = { git = "https://github.com/mvlabat/bevy_egui.git", branch = "egui-0.18"}

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui.git" }

```

Worked like a charm.  Now to go play with the newer table stuff in egui.

Closing this issue.  Thanks again!
