### ISSUE TITLE
remove dependency of winit / bevy_winit

### ISSUE THREAD

**Issue by coderedart** [mvlabat/bevy_egui#93]
I'm trying to use a glfw backend for bevy instead of the default bevy_winit backend. I wanted to use `bevy_egui` and `bevy_inspector_egui`, but `bevy_egui` explicitly depends on winit. I was hoping to feature-gate those code parts or make them generic traits so that bevy_egui can be more.. portable (?). 

places where winit specific code is used:
1. a couple workarounds for scroll delta https://github.com/mvlabat/bevy_egui/blob/main/src/systems.rs#L198
2. setting cursoricon which is gated behind clipboard feature https://github.com/mvlabat/bevy_egui/blob/main/src/systems.rs#L365

I think they are *that* important to keep `bevy_egui` specific to only winit backend.

**Comment by mvlabat** [comment]
The next release should be able to work without depending on `winit`: https://github.com/mvlabat/bevy_egui/pull/99.
I'll merge and publish it as soon as the new Egui version lands.
