### ISSUE TITLE
Provide Description on How to Adjust Scene Render Window

### ISSUE THREAD

**Issue by justacec** [mvlabat/bevy_egui#97]
I currently have an app with an egui::SidePanel on the left and an egui::TopBottomPanel on the bottom.  This is working great.  Now if I go to Bevy and add an obj file and render it, I can see that the panels are simply drawn on top of the scene rendering context.  What I would like is for the the rendering scene to fill the space that is not covered by the panels.  So, shifted to the upper right area of the window, in this way, the world point (0, 0, 0) would be at the center of the un-paneled space.  (does this make sense)

I am not sure how to make this adjustment, I have been going though the Bevy docs but did not see anything there.  Thought it might be in one of the bevy_egui examples but it does not seem so.

Can this be done?  If so, can you add some documentation to point peeps in the right direction?  :).

**Comment by mvlabat** [comment]
Hi! Yeah, your question totally makes sense. Quite a few people asked for the same example before, so I made one:
https://github.com/mvlabat/bevy_egui/blob/6eb02a2c8819c489fd2a509e02f25a617c042ed8/examples/side_panel.rs

And here's the video demonstrating how it works:
https://github.com/mvlabat/bevy_egui/issues/30#issuecomment-1046355742

Let me know if that's what you were looking for and whether it helps.

**Comment by justacec** [comment]
That is super cool.  Thanks.  I will see if that does what I was looking for (hint: I have no doubt).  Only thing left to do is add it to the examples dir.  :)

**Comment by mvlabat** [comment]
It is in the example dir (the example is called `side_panel.rs`). But I thought about adding some kind of breakdown of the examples with their descriptions to the README, to make navigation easier.

**Comment by justacec** [comment]
I will now walk to the corner and assume the fetal position for a few minutes.  ;)

Sorry, I thought I looked there for an example like this but just missed it.  Thanks for the pointer.

I am going to close this issue.

**Comment by mvlabat** [comment]
No worries! It's good we sorted it out :)
